#pragma once

enum game_type
{
    GAME_TYPE_UNSPECIFIED,
    GAME_TYPE_NORMAL,
    GAME_TYPE_TUTORIAL,
    GAME_TYPE_ARENA,
    GAME_TYPE_SPRINT,
    GAME_TYPE_HINTS,
#if TAG_MAJOR_VERSION == 34
    GAME_TYPE_ZOTDEF,
#endif
    GAME_TYPE_INSTRUCTIONS,
    GAME_TYPE_HIGH_SCORES,
    GAME_TYPE_CUSTOM_SEED,
    GAME_TYPE_IRONMAN,
    NUM_GAME_TYPE
};
